---
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  hosts:
    - pihole.home
  tls:
  - hosts:
    - pihole.home
    secretName: pihole-cert
serviceWeb:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1