repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: kubernetes-dashboard 
    url: https://kubernetes.github.io/dashboard/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
---
releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.6.2
    values:
      - ./values/longhorn.values.yml

  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.7

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.0
    values:
      - ./values/pihole.values.yml

  # Ingress for local network
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.1
    values:
      - ./values/nginx-internal.values.yml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.2.3
    values:
      - ./values/externaldns.values.yml

  # Certificate Manager
  - name: cert-manager
    namespace: cert-manager-system
    chart: jetstack/cert-manager
    version: 1.15.1
    values:
      - ./values/cert-manager.values.yml

  # Kubernetes Container Dashboard
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 7.5.0
    values:
      - ./values/kubernetes-dashboard.values.yml

  # Prometheus
  - name: prometheus
    namespace: prometheus-system
    chart: prometheus-community/prometheus
    version: 25.24.1
    values:
      - ./values/prometheus.values.yml

  # Grafana
  - name: grafana
    namespace: prometheus-system
    chart: grafana/grafana
    version: 8.3.7
    values:
      - ./values/grafana.values.yml
