repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kubernetes-dashboard 
    url: https://kubernetes.github.io/dashboard/
---
releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.6.2

  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.7

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.0
    values:
      - ./values/pihole.values.yml

  # Ingress for local network
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.1
    values:
      - ./values/nginx-internal.values.yml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.2.3
    values:
      - ./values/externaldns.values.yml

  # # Kubernetes Container Dashboard
  # - name: kubernetes-dashboard
  #   chart: kubernetes-dashboard/kubernetes-dashboard
  #   version: 7.5.0
  #   namespace: kubernetes-dashboard
  #   values:
  #     - ./values/kubernetes-dashboard.values.yml
