apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-authority-issuer
  namespace: cert-manager-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-authority-issuer-cert
  namespace: cert-manager-system
spec:
  isCA: true
  commonName: selfsigned-authority-issuer-cert
  subject:
    organizations:
      - ACME Inc.
    organizationalUnits:
      - Widgets
  secretName: selfsigned-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-authority-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  ca:
    secretName: selfsigned-key-pair