apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Your email address for registration and recovery contact
    email: michael@michaelmcguinness.net
    # Secret name used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer
    # Enable the HTTP-01 challenge mechanism
    solvers:
    - http01:
        ingress:
          class: nginx-internal  # Change to your ingress class if necessary