apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft-system
  labels:
    app: minecraft
spec:
  ports:
  - name: server
    port: 25565
  selector:
    app: minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft-system
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21-graalvm
        ports:
        - name: server
          containerPort: 25565
        - name: rcon
          containerPort: 25575
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        env:
        - name: SERVER_NAME
          value: McLads
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: VANILLA
        - name: VERSION
          value: "1.21"
        - name: RCON_PASSWORD
          value: "TOP_SECRET"
        - name: DIFFICULTY
          value: easy
        - name: MAX_PLAYERS
          value: "10"
        - name: MODE
          value: survival
        - name: LEVEL_TYPE
          value: "minecraft:default"
        # - name: DEBUG
        #   value: "TRUE"
        # - name: OVERRIDE_SERVER_PROPERTIES
        #   value: "TRUE"
        # - name: MOTD
        #   value: "TRUE"
        # - name: INIT_MEMORY
        #   value: 2G
        # - name: MAX_MEMORY
        #   value: 10G
        # - name: ENABLE_ROLLING_LOGS
        #   value: "true"
        # - name: ONLINE_MODE
        #   value: "true"
        # - name: ENABLE_WHITELIST
        #   value: "false"
        # - name: OVERRIDE_WHITELIST
        #   value: "true"
        # - name: ENABLE_AUTOPAUSE
        #   value: "true"
        # - name: WHITELIST
        #   value: ""
        # resources:
        #   requests:
        #     cpu: 1000m
        #     memory: 1Gi
        #   limits:
        #     cpu: 3000m 
        #     memory: 8Gi
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data
      namespace: minecraft-system
    spec:
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi
      accessModes:
        - ReadWriteOnce